const PERF_START=performance.now();let cachedVideoId=null;let videoIdCacheValid=!1;let videoIdCacheTimestamp=null;const VIDEO_ID_CACHE_DURATION=60000;function invalidateVideoIdCache(){cachedVideoId=null;videoIdCacheValid=!1;videoIdCacheTimestamp=null}
function waitForDependencies(retries=0){const maxRetries=100;if(typeof Hls==='undefined'||!document.getElementById('video-container')){if(retries<maxRetries){setTimeout(()=>waitForDependencies(retries+1),50)}
return}
initializePlayer()}
function injectCriticalCSS(){if(document.getElementById('critical-css'))return;const criticalCSS=`
        .cerberus-video-container{opacity:1;transition:opacity .3s ease}
        .cerberus-video-container.loaded{opacity:1}
        .cerberus-video-loader{position:absolute;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.8);display:flex;align-items:center;justify-content:center;z-index:1000}
        .cerberus-spinner{width:40px;height:40px;border:3px solid #f3f3f3;border-top:3px solid #3498db;border-radius:50%;animation:spin 1s linear infinite}
        @keyframes spin{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}
    `;const style=document.createElement('style');style.id='critical-css';style.textContent=criticalCSS;document.head.appendChild(style)}
injectCriticalCSS();waitForDependencies();function initializePlayer(){const initStart=performance.now();const videoContainer=document.getElementById('video-container');const video=document.getElementById('cerberus-video');const progress=document.getElementById('progress');const thumbnail=document.getElementById('thumbnail');const videoSrc=video.getAttribute('data-video-src');let firstPlay=!0;const videoIdMatch=(videoSrc&&videoSrc.trim()!=='')?videoSrc.match(/([a-f0-9\-]{36})/):null;const videoSpeed=parseFloat(video.getAttribute('data-video-speed'))||1;const videoDuplicate=document.querySelector('[data-video-duplicate]');const videoIdDuplicate=videoDuplicate?videoDuplicate.getAttribute('data-video-duplicate'):null;function getCurrentVideoId(){const now=Date.now();if(cachedVideoId&&videoIdCacheTimestamp&&(now-videoIdCacheTimestamp)<VIDEO_ID_CACHE_DURATION){return cachedVideoId}
if(abTestGroupId&&abTestConfig){const groupVideoSrc=abTestConfig.videoSrc;if(groupVideoSrc){const videoIdMatch=groupVideoSrc.match(/([a-f0-9\-]{36})/);if(videoIdMatch&&videoIdMatch[1]){cachedVideoId=videoIdMatch[1];videoIdCacheValid=!0;videoIdCacheTimestamp=now;return cachedVideoId}}}
const videoDuplicateElement=document.querySelector('[data-video-duplicate]');if(videoDuplicateElement){const duplicateId=videoDuplicateElement.getAttribute('data-video-duplicate');if(duplicateId){cachedVideoId=duplicateId;videoIdCacheValid=!0;videoIdCacheTimestamp=now;return cachedVideoId}}
if(videoIdMatch&&videoIdMatch[1]){cachedVideoId=videoIdMatch[1];videoIdCacheValid=!0;videoIdCacheTimestamp=now;return cachedVideoId}
return null}
function getCurrentVideoSrc(){const currentVideoSrc=video.getAttribute('data-video-src');if(currentVideoSrc&&currentVideoSrc.trim()!==''){return currentVideoSrc}
if(typeof updatedVideoSrc!=='undefined'&&updatedVideoSrc&&updatedVideoSrc.trim()!==''){return updatedVideoSrc}
if(videoSrc&&videoSrc.trim()!==''){return videoSrc}
return null}
window.getCurrentVideoId=getCurrentVideoId;window.getCurrentVideoSrc=getCurrentVideoSrc;window.sendEvent=sendEvent;Object.defineProperty(window,'userHasInteracted',{get:function(){return userHasInteracted}});Object.defineProperty(window,'userReallyInteracted',{get:function(){return userReallyInteracted}});Object.defineProperty(window,'exitEventSent',{get:function(){return exitEventSent}});window.markUserInteraction=markUserInteraction;Object.defineProperty(window,'videoEndedSent',{get:function(){return videoEndedSent}});Object.defineProperty(window,'videoHasEnded',{get:function(){return videoHasEnded}});let videoId=null;if(videoDuplicate&&videoIdDuplicate){videoId=videoIdDuplicate}else if(videoIdMatch&&videoIdMatch[1]){videoId=videoIdMatch[1]}else if(videoSrc&&videoSrc.trim()!==''){const fallbackMatch=videoSrc.match(/([a-f0-9\-]{36})/);if(fallbackMatch&&fallbackMatch[1]){videoId=fallbackMatch[1]}}
let abTestGroupId=null;const SECONDS_TO_DISPLAY=parseInt(video.getAttribute('data-seconds-to-display'))||1770;const alreadyDisplayedKey='elementsDisplayed';const hiddenElement=document.querySelector('[data-hidden-targets]');const hiddenSelector=hiddenElement?hiddenElement.getAttribute('data-hidden-targets'):null;let elsHidden=null;if(hiddenSelector&&hiddenSelector.trim()!==''&&hiddenSelector!=='.'){try{elsHidden=document.querySelectorAll(hiddenSelector)}catch(error){elsHidden=[]}}else{elsHidden=[]}
const loader=document.getElementById('video-loader');const pauseOverlay=document.getElementById('pauseOverlay');const AUTOPLAY_LOOP_DURATION=10;const BUFFER_LIMIT_SECONDS=10;let UNIQUE_VIEW_KEY=`uniqueView_${videoId || 'unknown'}`;let PAGE_ACCESS_KEY=`pageAccess_${videoId || 'unknown'}`;let autoplayLoopActive=!1;let autoplayLoopTimer=null;let uniqueViewMarked=!1;let pageAccessSent=!1;let abTestGroup=null;let abTestConfig=null;let isNewUser=!0;let bufferLimited=!1;let thumbnailHiddenByUser=!1;let isPageReload=!1;loader.style.display='flex';videoContainer.classList.remove('loaded');let playerSuccessfullyInitialized=!1;const FALLBACK_SCRIPT_SRC='https://cvault.b-cdn.net/videoPlayerFallback.js';const FALLBACK_TIMEOUT=5000;let fallbackCheckTimer=null;let fallbackLoaded=!1;let finalSpeed=videoSpeed;let finalProgressPower=0.33;let testSpeedEnabled=!1;let testProgressEnabled=!1;let initialSetupComplete=!1;function getAllURLParameters(){const urlParams=new URLSearchParams(window.location.search);const allParams={};urlParams.forEach((value,key)=>{allParams[key]=value;localStorage.setItem(key,value)});return allParams}
function getVisitorId(){let visitorId=localStorage.getItem('visitorId');if(!visitorId){visitorId=`visitor_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;localStorage.setItem('visitorId',visitorId)}
return visitorId}
const allURLParams=getAllURLParameters();const visitorId=getVisitorId();function getReferral(){let referral=document.referrer||'direct';if(referral===''||referral==='direct'){if(allURLParams.utm_source){referral=allURLParams.utm_source}else if(allURLParams.ref_id){referral=allURLParams.ref_id}else if(allURLParams.cmc_adid){referral='cmc_'+allURLParams.cmc_adid}else{referral='direct'}}
localStorage.setItem('referral',referral);return referral}
const referral=getReferral();detectPageReload();let progressUpdateInterval=null;let lastProgressTime=0;const PROGRESS_UPDATE_INTERVAL=5000;let userHasInteracted=!1;let userReallyInteracted=!1;let exitEventSent=!1;let pauseEventTimeout=null;let lastPauseTime=null;let lastCriticalEvent=null;let videoEndedSent=!1;let videoHasEnded=!1;function sendEvent(eventType,currentTime=0,additionalData={}){if(eventType==='video_load_time'){return}
const currentVideoId=getCurrentVideoId();const eventData={videoId:currentVideoId,userId:visitorId,event:eventType,currentTime:parseFloat(currentTime),referral:referral,isPageReload:isPageReload,abTestGroup:abTestGroupId,...additionalData,...allURLParams};const criticalEvents=['beforeunload','pagehide','visibilitychange','ended'];if(criticalEvents.includes(eventType)){sendCriticalEvent(currentTime,eventType,eventData)}else{setTimeout(()=>{fetch('https://view.cerberusvault.com/save-event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(eventData),}).catch(()=>{})},0)}}
function startProgressUpdate(){if(progressUpdateInterval)return;progressUpdateInterval=setInterval(()=>{if(!video.paused&&video.currentTime>0&&userReallyInteracted){const currentTime=video.currentTime;if(Math.abs(currentTime-lastProgressTime)>=1){lastProgressTime=currentTime;fetch('https://view.cerberusvault.com/update-progress',{method:'POST',headers:{'Content-Type':'application/json',},body:JSON.stringify({videoId:getCurrentVideoId(),userId:visitorId,currentTime:currentTime,abTestGroup:abTestGroupId,}),}).catch((error)=>{if(!error.message?.includes('Failed to fetch')&&!error.message?.includes('ERR_CONNECTION_REFUSED')){console.error('Erro ao enviar atualização de progresso:',error)}})}}},PROGRESS_UPDATE_INTERVAL)}
function stopProgressUpdate(){if(progressUpdateInterval){clearInterval(progressUpdateInterval);progressUpdateInterval=null}}
function initializeABTest(){const abTestEnabled=video.getAttribute('data-ab-test')==='true';if(!abTestEnabled)return null;const groups=['A','B','C','D','E'];const availableGroups=[];groups.forEach(group=>{const videoSrc=video.getAttribute(`data-video-group-${group.toLowerCase()}`);const groupId=video.getAttribute(`data-group-id-${group.toLowerCase()}`);if(videoSrc){const config={group:group,groupId:groupId,videoSrc:videoSrc,callToPlay:video.getAttribute(`data-thumbnail-group-${group.toLowerCase()}`)||null,imagePause:video.getAttribute(`data-pause-image-group-${group.toLowerCase()}`)||null,poster:video.getAttribute(`data-poster-group-${group.toLowerCase()}`)||null,speed:parseFloat(video.getAttribute(`data-speed-group-${group.toLowerCase()}`))||videoSpeed,desktopSize:parseInt(video.getAttribute(`data-desktop-size-group-${group.toLowerCase()}`))||55,mobileSize:parseInt(video.getAttribute(`data-mobile-size-group-${group.toLowerCase()}`))||95,progressBarColor:video.getAttribute(`data-progress-color-group-${group.toLowerCase()}`)||'#ff5722',progressBarHeight:parseInt(video.getAttribute(`data-progress-height-group-${group.toLowerCase()}`))||5,progressBarSpeed:parseFloat(video.getAttribute(`data-progress-speed-group-${group.toLowerCase()}`))||1,overlayColor:video.getAttribute(`data-overlay-color-group-${group.toLowerCase()}`)||'#bc03ff',secondsToDisplay:parseInt(video.getAttribute(`data-seconds-display-group-${group.toLowerCase()}`))||SECONDS_TO_DISPLAY,hiddenTargets:video.getAttribute(`data-hidden-targets-group-${group.toLowerCase()}`)||hiddenSelector};availableGroups.push(config)}});if(availableGroups.length===0){return null}
const testKey=`abTest_${videoId || 'unknown'}`;const existingGroup=localStorage.getItem(testKey);if(existingGroup&&availableGroups.find(g=>g.group===existingGroup)){abTestGroup=existingGroup;abTestConfig=availableGroups.find(g=>g.group===existingGroup)}else{const randomIndex=Math.floor(Math.random()*availableGroups.length);abTestConfig=availableGroups[randomIndex];abTestGroup=abTestConfig.group;localStorage.setItem(testKey,abTestGroup)}
abTestGroupId=abTestConfig.groupId;video.setAttribute('data-video-src',abTestConfig.videoSrc);video.setAttribute('data-video-speed',abTestConfig.speed);video.setAttribute('data-progress-bar-speed',abTestConfig.progressBarSpeed);video.setAttribute('data-seconds-to-display',abTestConfig.secondsToDisplay);video.setAttribute('data-hidden-targets',abTestConfig.hiddenTargets);if(abTestConfig.poster){video.setAttribute('poster',abTestConfig.poster)}
videoContainer.setAttribute('data-ab-test-group',abTestGroup);videoContainer.setAttribute('data-desktop-size',abTestConfig.desktopSize);videoContainer.setAttribute('data-mobile-size',abTestConfig.mobileSize);if(abTestConfig.callToPlay&&thumbnail){thumbnail.src=abTestConfig.callToPlay}
if(progress){progress.style.backgroundColor=abTestConfig.progressBarColor}
const progressBarElement=document.getElementById('progressBar');if(progressBarElement){progressBarElement.style.height=`${abTestConfig.progressBarHeight}px`;progressBarElement.style.display='block'}
const overlayElement=document.getElementById('overlay');if(overlayElement){overlayElement.style.backgroundColor=abTestConfig.overlayColor}
if(abTestConfig.imagePause&&pauseOverlay){let pauseImage=pauseOverlay.querySelector('.cerberus-pause-image');if(!pauseImage){pauseImage=document.createElement('img');pauseImage.className='cerberus-pause-image';pauseImage.style.cssText=`
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            max-width: 80%;
            max-height: 80%;
            z-index: 10;
            pointer-events: none;
         `;const pauseText=pauseOverlay.querySelector('.cerberus-pause-text');if(pauseText){pauseText.style.display='none'}
pauseOverlay.appendChild(pauseImage)}
pauseImage.src=abTestConfig.imagePause}else{const pauseText=pauseOverlay.querySelector('.cerberus-pause-text');if(pauseText){pauseText.style.display='block'}
const pauseImage=pauseOverlay.querySelector('.cerberus-pause-image');if(pauseImage){pauseImage.remove()}}
finalSpeed=abTestConfig.speed;videoId=getCurrentVideoId();UNIQUE_VIEW_KEY=`uniqueView_${videoId}`;PAGE_ACCESS_KEY=`pageAccess_${videoId}`;invalidateVideoIdCache();return abTestConfig.videoSrc}
function sendPageAccess(){if(pageAccessSent)return;pageAccessSent=!0;const currentVideoId=getCurrentVideoId();if(currentVideoId){localStorage.setItem(`pageAccess_${currentVideoId}`,'true')}
setTimeout(()=>{const progressData=loadVideoProgress();let currentTimeToSend=0;if(progressData&&progressData.currentTime>0){currentTimeToSend=progressData.currentTime}
const testData=getTestData();fetch('https://view.cerberusvault.com/save-progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({videoId:currentVideoId,userId:visitorId,currentTime:currentTimeToSend,evento:'page_access',abTestGroup:abTestGroupId,isPageReload:isPageReload,hasProgress:progressData!==null,progressCompleted:progressData?progressData.completed:!1,...testData,...allURLParams}),}).catch(()=>{})},100)}
function markUniqueView(){const currentVideoId=getCurrentVideoId();if(!currentVideoId)return;const uniqueViewKey=`uniqueView_${currentVideoId}`;if(uniqueViewMarked||localStorage.getItem(uniqueViewKey))return;uniqueViewMarked=!0;localStorage.setItem(uniqueViewKey,'true');const testData=getTestData();fetch('https://view.cerberusvault.com/save-progress',{method:'POST',headers:{'Content-Type':'application/json',},body:JSON.stringify({videoId:currentVideoId,userId:visitorId,currentTime:video.currentTime,evento:'unique_view',abTestGroup:abTestGroupId,...testData,...allURLParams}),}).catch((error)=>{if(!error.message?.includes('Failed to fetch')&&!error.message?.includes('ERR_CONNECTION_REFUSED')){console.error('Erro ao enviar unique view:',error)}})}
function getTestData(){const testData={};if(testSpeedEnabled){testData.testSpeed=finalSpeed}
if(testProgressEnabled){testData.testProgressPower=finalProgressPower}
return testData}
function sendCriticalEvent(currentTime,evento,eventData={}){const currentVideoId=getCurrentVideoId();const eventKey=`${evento}_${currentVideoId}_${parseFloat(currentTime).toFixed(2)}`;if(lastCriticalEvent===eventKey){return}
lastCriticalEvent=eventKey;const testData=getTestData();const data=JSON.stringify({videoId:currentVideoId,userId:visitorId,currentTime:parseFloat(currentTime),evento:evento,abTestGroup:abTestGroupId,referral:referral,userReallyInteracted:userReallyInteracted,...testData,...allURLParams,...eventData});if(navigator.sendBeacon){const sent=navigator.sendBeacon('https://view.cerberusvault.com/save-progress',data);if(sent){return}}
try{const xhr=new XMLHttpRequest();xhr.open('POST','https://view.cerberusvault.com/save-progress',!1);xhr.setRequestHeader('Content-Type','application/json');xhr.send(data)}catch(error){console.error(`[BunnyQA] Falha ao enviar evento crítico ${evento}:`,error)}}
const abTestVideoSrc=initializeABTest();const finalVideoSrc=abTestVideoSrc||getCurrentVideoSrc();const updatedVideoSrc=video.getAttribute('data-video-src');const updatedVideoIdMatch=updatedVideoSrc?updatedVideoSrc.match(/([a-f0-9\-]{36})/):null;if(!finalVideoSrc){loadFallbackScript()}
setTimeout(()=>sendPageAccess(),0);setTimeout(()=>startAutoplayLoop(),1000);function finalizeVideoLoad(){if(fallbackLoaded||playerSuccessfullyInitialized)return;playerSuccessfullyInitialized=!0;const finalizeStart=performance.now();const totalLoadTime=finalizeStart-PERF_START;const videoLoadTime=initStart?finalizeStart-initStart:0;if(fallbackCheckTimer){clearTimeout(fallbackCheckTimer);fallbackCheckTimer=null}
if(window.loaderObserverForFallback){window.loaderObserverForFallback.disconnect();window.loaderObserverForFallback=null}
requestAnimationFrame(()=>{const currentLoader=document.getElementById('video-loader');if(currentLoader){currentLoader.style.display='none';setTimeout(()=>currentLoader.remove(),300)}
if(videoContainer){videoContainer.classList.add('loaded');videoContainer.style.opacity='1';videoContainer.style.transform='translateZ(0)';videoContainer.style.willChange='auto'}
const video=document.getElementById('cerberus-video');if(video&&video.poster){const thumbnail=document.getElementById('thumbnail');if(thumbnail&&video.paused&&video.currentTime===0){thumbnail.style.opacity='0.3';thumbnail.style.zIndex='50'}}});setTimeout(()=>{if(typeof sendEvent==='function'){try{sendEvent('video_load_time',0,{totalLoadTimeMs:totalLoadTime,videoLoadTimeMs:videoLoadTime,performanceScore:totalLoadTime<2000?'excellent':totalLoadTime<4000?'good':'needs_improvement'})}catch(e){}}},0);setTimeout(()=>{startAutoplayLoop()},0)}
function loadFallbackScript(){if(fallbackLoaded)return;fallbackLoaded=!0;playerSuccessfullyInitialized=!1;if(fallbackCheckTimer){clearTimeout(fallbackCheckTimer);fallbackCheckTimer=null}
if(window.loaderObserverForFallback){window.loaderObserverForFallback.disconnect();window.loaderObserverForFallback=null}
const cacheBustedSrc=FALLBACK_SCRIPT_SRC+'?t='+Date.now();const script=document.createElement('script');script.src=cacheBustedSrc;script.onload=()=>{};script.onerror=()=>{};document.body.appendChild(script)}
if(localStorage.getItem(alreadyDisplayedKey)==="true"){showHiddenElements()}
function showHiddenElements(){if(elsHidden&&elsHidden.length>0){try{const elements=Array.from(elsHidden);elements.forEach(element=>{if(element&&element.style){element.style.display='block'}});localStorage.setItem(alreadyDisplayedKey,"true")}catch(error){}}}
function getRandomValue(min,max){return Math.random()*(max-min)+min}
if(Hls.isSupported()){if(!finalVideoSrc){loadFallbackScript()}else{const hlsConfig={startLevel:0,maxBufferLength:8,maxBufferSize:20*1000*1000,maxBufferHole:0.5,capLevelToPlayerSize:!0,maxMaxBufferLength:15,progressive:!0,enableWorker:!0,autoStartLoad:!0,testBandwidth:!1,lowLatencyMode:!0,abrEwmaFastLive:2.0,abrEwmaSlowLive:6.0,abrMaxWithRealBitrate:!1,maxStarvationDelay:2,maxLoadingDelay:2,backBufferLength:5,};const hls=new Hls(hlsConfig);window.hlsInstance=hls;const originalPoster=video.poster;hls.loadSource(finalVideoSrc);hls.attachMedia(video);if(originalPoster&&!video.poster){video.poster=originalPoster}
hls.on(Hls.Events.MANIFEST_PARSED,function(){if(originalPoster&&video.poster!==originalPoster){video.poster=originalPoster}
video.muted=!0;const shouldAutoplay=!isPageReload&&(!localStorage.getItem('videoProgress')||parseFloat(localStorage.getItem('videoProgress'))===0);if(shouldAutoplay){const playPromise=video.play();if(playPromise!==undefined){playPromise.then(()=>{finalizeVideoLoad()}).catch(error=>{if(error.name==='NotAllowedError'){loadFallbackScript()}})}}else{finalizeVideoLoad()}});hls.on(Hls.Events.ERROR,function(event,data){if(data.fatal){if(!fallbackLoaded){loadFallbackScript()}}})}}else if(video.canPlayType('application/vnd.apple.mpegurl')){if(!finalVideoSrc){loadFallbackScript()}else{video.src=finalVideoSrc;video.preload="metadata";video.addEventListener('loadedmetadata',function(){video.muted=!0;const shouldAutoplay=!isPageReload&&(!localStorage.getItem('videoProgress')||parseFloat(localStorage.getItem('videoProgress'))===0);if(shouldAutoplay){const playPromise=video.play();if(playPromise!==undefined){playPromise.then(()=>{finalizeVideoLoad()}).catch(error=>{if(error.name==='NotAllowedError'){loadFallbackScript()}})}}else{finalizeVideoLoad()}});video.addEventListener('error',(e)=>{if(!fallbackLoaded){loadFallbackScript()}})}}else{loadFallbackScript()}
video.addEventListener('loadedmetadata',()=>{const checkDimensions=()=>{const videoWidth=video.videoWidth;const videoHeight=video.videoHeight;if(videoWidth>0&&videoHeight>0){videoContainer.classList.remove('video-horizontal','video-vertical','video-3x4');const aspectRatio=videoWidth/videoHeight;if(aspectRatio>1.2){videoContainer.classList.add('video-horizontal')}else if(aspectRatio>=0.6&&aspectRatio<=0.8){videoContainer.classList.add('video-3x4')}else{videoContainer.classList.add('video-vertical')}
setupInitialState()}else{setTimeout(checkDimensions,100)}};const setupInitialState=()=>{if(initialSetupComplete){return}
cleanOldVideoProgress();const progressData=loadVideoProgress();let savedTime=progressData?progressData.currentTime.toString():null;if(savedTime&&parseFloat(savedTime)>0){if(document.getElementById('overlay')){document.getElementById('overlay').style.display='flex';if(thumbnail)thumbnail.style.display='none'}
if(thumbnail&&video.paused&&!playerSuccessfullyInitialized){thumbnail.style.display='block'}
initialSetupComplete=!0;finalizeVideoLoad()}
testSpeedEnabled=video.getAttribute('data-test-speed')==='true';if(testSpeedEnabled){const testSpeedMin=parseFloat(video.getAttribute('data-test-speed-min')||'1');const testSpeedMax=parseFloat(video.getAttribute('data-test-speed-max')||'2');const randomSpeed=getRandomValue(testSpeedMin,testSpeedMax);finalSpeed=parseFloat(randomSpeed.toFixed(2))||(testSpeedMin+testSpeedMax)/2;videoContainer.setAttribute('data-test-speed-value',finalSpeed)}
testProgressEnabled=video.getAttribute('data-test-progress-speed')==='true';const progressBarSpeedAttr=video.getAttribute('data-progress-bar-speed');if(testProgressEnabled){const testProgressMin=parseFloat(video.getAttribute('data-test-progress-speed-min')||'0.25');const testProgressMax=parseFloat(video.getAttribute('data-test-progress-speed-max')||'0.8');const randomPower=getRandomValue(testProgressMin,testProgressMax);finalProgressPower=parseFloat(randomPower.toFixed(2))||(testProgressMin+testProgressMax)/2;videoContainer.setAttribute('data-test-progress-value',finalProgressPower)}else if(progressBarSpeedAttr!==null){const parsedPower=parseFloat(progressBarSpeedAttr);if(!isNaN(parsedPower)&&parsedPower>0){finalProgressPower=parsedPower;videoContainer.setAttribute('data-progress-value',finalProgressPower)}}
if(video.playbackRate!==finalSpeed){video.playbackRate=finalSpeed}
if(!playerSuccessfullyInitialized){finalizeVideoLoad()}};checkDimensions()},{once:!0});video.setAttribute('playsInline','true');video.addEventListener('click',()=>{const isFirstInteraction=!userReallyInteracted;firstPlay=!1;markUserInteraction();const timeToSend=isFirstInteraction?0:video.currentTime;if(video.paused){video.muted=!1;video.play();document.getElementById('pauseOverlay').style.display='none';thumbnail.style.display='none'}else{video.pause();document.getElementById('pauseOverlay').style.display='flex'}});document.getElementById('pauseOverlay').addEventListener('click',()=>{const isFirstInteraction=!userReallyInteracted;firstPlay=!1;const timeToSend=isFirstInteraction?0:video.currentTime;markUserInteraction();video.muted=!1;video.play();document.getElementById('pauseOverlay').style.display='none';thumbnail.style.display='none'});video.addEventListener('timeupdate',()=>{if(!firstPlay){const normalizedTime=video.currentTime/video.duration;const adjustedProgress=Math.pow(Math.max(0,normalizedTime),finalProgressPower);const progressPercent=adjustedProgress*100;progress.style.width=`${progressPercent}%`;if(video.currentTime===0&&!thumbnailHiddenByUser){thumbnail.style.display='block'}
if(userReallyInteracted){saveVideoProgress(video.currentTime)}
const currentSecondsToDisplay=abTestConfig?abTestConfig.secondsToDisplay:SECONDS_TO_DISPLAY;if(video.currentTime>=currentSecondsToDisplay&&!localStorage.getItem(alreadyDisplayedKey)){showHiddenElements()}}});function adjustVideoSize(){const desktopSize=videoContainer.getAttribute('data-desktop-size');const mobileSize=videoContainer.getAttribute('data-mobile-size');const viewportWidth=window.visualViewport?window.visualViewport.width/window.devicePixelRatio:window.innerWidth/window.devicePixelRatio;if(desktopSize&&mobileSize){const isMobile=viewportWidth<=768;videoContainer.style.width=isMobile?`${mobileSize}%`:`${desktopSize}%`}}
adjustVideoSize();window.addEventListener('resize',adjustVideoSize);document.getElementById('continueButton').addEventListener('click',()=>{const isFirstInteraction=!userReallyInteracted;const savedTime=localStorage.getItem('videoProgress');if(savedTime){video.currentTime=parseFloat(savedTime);firstPlay=!1;video.muted=!1;video.play();const timeToSend=isFirstInteraction?parseFloat(savedTime):parseFloat(savedTime);markUserInteraction(!1)}
document.getElementById('overlay').style.display='none'});document.getElementById('restartButton').addEventListener('click',()=>{const isFirstInteraction=!userReallyInteracted;video.currentTime=0.1;clearVideoProgress();firstPlay=!1;video.muted=!1;video.play();markUserInteraction();document.getElementById('overlay').style.display='none'});thumbnail.addEventListener('click',()=>{const isFirstInteraction=!userReallyInteracted;markUserInteraction();const timeToSend=isFirstInteraction?0:video.currentTime;firstPlay=!1;video.muted=!1;video.play();thumbnail.style.display='none';thumbnailHiddenByUser=!0;const overlayElement=document.getElementById('overlay');if(overlayElement)overlayElement.style.display='none'});function sendProgress(currentTime,evento){const currentVideoId=getCurrentVideoId();const testData=getTestData();fetch('https://view.cerberusvault.com/save-progress',{method:'POST',headers:{'Content-Type':'application/json',},body:JSON.stringify({videoId:currentVideoId,userId:visitorId,currentTime:parseFloat(currentTime),evento:evento,abTestGroup:abTestGroupId,userReallyInteracted:userReallyInteracted,...testData,...allURLParams}),}).catch((error)=>{if(!error.message?.includes('Failed to fetch')&&!error.message?.includes('ERR_CONNECTION_REFUSED')){console.error('Erro ao enviar progresso:',error)}})}
function sendProgressWithBeacon(currentTime,evento){const currentVideoId=getCurrentVideoId();const testData=getTestData();const data=JSON.stringify({videoId:currentVideoId,userId:visitorId,currentTime:parseFloat(currentTime),evento:evento,abTestGroup:abTestGroupId,userReallyInteracted:userReallyInteracted,...testData,...allURLParams});navigator.sendBeacon('https://view.cerberusvault.com/save-progress',data)}
video.addEventListener('pause',()=>{if(videoHasEnded){return}
if(userReallyInteracted){const currentTime=video.currentTime;if(lastPauseTime!==null&&Math.abs(currentTime-lastPauseTime)<0.1){return}
if(pauseEventTimeout){clearTimeout(pauseEventTimeout)}
pauseEventTimeout=setTimeout(()=>{if(videoHasEnded){return}
lastPauseTime=currentTime;sendProgress(localStorage.getItem('videoProgress')!==null?localStorage.getItem('videoProgress'):currentTime,'pause');pauseEventTimeout=null},500)}});video.addEventListener('ended',()=>{if(videoEndedSent){return}
videoHasEnded=!0;videoEndedSent=!0;if(pauseEventTimeout){clearTimeout(pauseEventTimeout);pauseEventTimeout=null}
if(userReallyInteracted){stopProgressUpdate();saveVideoProgress(video.duration);sendProgress(video.duration,'ended');markUniqueView();if(!localStorage.getItem(alreadyDisplayedKey)){showHiddenElements()}}
setTimeout(()=>{video.currentTime=0;video.pause();videoHasEnded=!1;videoEndedSent=!1;lastPauseTime=null;thumbnailHiddenByUser=!1;if(thumbnail){thumbnail.style.display='block'}},500)});window.addEventListener('pagehide',()=>{handlePageExit('pagehide')});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){handlePageExit('visibilitychange')}else if(document.visibilityState==='visible'){if(!exitEventSent){}
setTimeout(()=>{if(document.visibilityState==='visible'){exitEventSent=!1}},1000)}});window.addEventListener('beforeunload',(event)=>{handlePageExit('beforeunload')});window.addEventListener('load',()=>{if(!playerSuccessfullyInitialized&&!fallbackLoaded&&fallbackCheckTimer===null){console.log(`[BunnyQA] Configurando fallback timer para ${FALLBACK_TIMEOUT}ms`);fallbackCheckTimer=setTimeout(()=>{const loaderElement=document.getElementById('video-loader');const videoContainerElement=document.getElementById('video-container');const loaderVisible=loaderElement&&window.getComputedStyle(loaderElement).display!=='none';const containerNotLoaded=videoContainerElement&&!videoContainerElement.classList.contains('loaded');if(loaderVisible||containerNotLoaded){console.warn(`[BunnyQA] Player não foi inicializado após ${FALLBACK_TIMEOUT}ms - carregando fallback`);loadFallbackScript()}else{console.log('[BunnyQA] Player foi inicializado com sucesso antes do fallback')}
fallbackCheckTimer=null},FALLBACK_TIMEOUT)}});function cleanOldVideoProgress(){const keysToRemove=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key&&key.startsWith('videoProgress_')){try{const data=JSON.parse(localStorage.getItem(key));const daysSinceLastSave=(Date.now()-data.timestamp)/(1000*60*60*24);if(daysSinceLastSave>30){keysToRemove.push(key)}}catch(e){keysToRemove.push(key)}}}
keysToRemove.forEach(key=>{localStorage.removeItem(key)})}
function markUserInteraction(shouldResetFromLoop=!0){if(!userHasInteracted){userHasInteracted=!0;userReallyInteracted=!0;startProgressUpdate();if(autoplayLoopActive&&shouldResetFromLoop){video.currentTime=0}
stopAutoplayLoop()}
if(thumbnail){thumbnail.style.display='none';thumbnailHiddenByUser=!0}
markUniqueView()}
function startAutoplayLoop(){if(userReallyInteracted){return}
if(autoplayLoopActive){return}
autoplayLoopActive=!0;const loopControlHandler=()=>{if(userReallyInteracted){video.removeEventListener('timeupdate',loopControlHandler);autoplayLoopActive=!1;return}
if(video.currentTime>=BUFFER_LIMIT_SECONDS){video.currentTime=0;if(video.paused){video.play().catch(e=>console.log('[Loop] Autoplay bloqueado durante loop:',e))}}};video.addEventListener('timeupdate',loopControlHandler);if(video.paused){const playPromise=video.play();if(playPromise!==undefined){playPromise.catch(error=>{console.log('[Loop] Autoplay inicial falhou:',error.name)})}}}
function stopAutoplayLoop(){if(autoplayLoopTimer){clearTimeout(autoplayLoopTimer);autoplayLoopTimer=null}
autoplayLoopActive=!1}
function handlePageExit(eventType){if(exitEventSent){return}
exitEventSent=!0;let currentTime=0;const progressData=loadVideoProgress();if(progressData&&progressData.currentTime>0){currentTime=progressData.currentTime}else if(userReallyInteracted){const savedProgress=localStorage.getItem('videoProgress');const videoCurrentTime=video.currentTime||0;if(savedProgress!==null){currentTime=Math.max(parseFloat(savedProgress),videoCurrentTime)}else{currentTime=videoCurrentTime}}
sendCriticalEvent(currentTime,'page_exit',{exitType:eventType,hadProgressSaved:progressData!==null,hadSessionInteraction:userReallyInteracted})}
function getVideoProgressKey(){const currentVideoId=getCurrentVideoId();if(!currentVideoId)return null;return `videoProgress_${currentVideoId}_${visitorId}`}
let lastSavedProgressTime=0;const PROGRESS_SAVE_THRESHOLD=1;function saveVideoProgress(currentTime){if(!userReallyInteracted||currentTime<=0)return;if(Math.abs(currentTime-lastSavedProgressTime)<PROGRESS_SAVE_THRESHOLD){return}
const progressKey=getVideoProgressKey();if(!progressKey)return;const progressData={currentTime:parseFloat(currentTime),timestamp:Date.now(),completed:currentTime>=(video.duration*0.95),videoId:getCurrentVideoId(),duration:video.duration};localStorage.setItem(progressKey,JSON.stringify(progressData));localStorage.setItem('videoProgress',currentTime);lastSavedProgressTime=currentTime}
function loadVideoProgress(){const progressKey=getVideoProgressKey();if(!progressKey)return null;const saved=localStorage.getItem(progressKey);if(saved){try{const progressData=JSON.parse(saved);const daysSinceLastSave=(Date.now()-progressData.timestamp)/(1000*60*60*24);if(daysSinceLastSave>7){clearVideoProgress();return null}
return progressData}catch(e){clearVideoProgress()}}
const oldProgress=localStorage.getItem('videoProgress');if(oldProgress&&parseFloat(oldProgress)>0){return{currentTime:parseFloat(oldProgress),timestamp:Date.now(),completed:!1}}
return null}
function clearVideoProgress(){const progressKey=getVideoProgressKey();if(progressKey){localStorage.removeItem(progressKey)}
localStorage.removeItem('videoProgress')}
function detectPageReload(){const lastLoadTime=sessionStorage.getItem('pageLoadTime');const currentTime=Date.now();if(lastLoadTime){const timeDiff=currentTime-parseInt(lastLoadTime);isPageReload=timeDiff<30000}else{isPageReload=!1}
sessionStorage.setItem('pageLoadTime',currentTime.toString());return isPageReload}}
function createCerberusContextMenuAt(x,y){const old=document.getElementById('cerberus-context-menu');if(old)old.remove();const btn=document.createElement('a');btn.id='cerberus-context-menu';btn.className='cerberus-context-menu-btn-minimal';btn.href='https://cerberusvault.com/';btn.target='_blank';btn.rel='noopener noreferrer';btn.textContent='Conheça a Cerberus Vault';btn.style.position='fixed';btn.style.left=x+'px';btn.style.top=y+'px';btn.style.zIndex=99999;document.body.appendChild(btn);setTimeout(()=>{document.addEventListener('mousedown',function handler(e){if(!btn.contains(e.target)){btn.remove();document.removeEventListener('mousedown',handler)}})},10);btn.addEventListener('click',()=>btn.remove())}
function addContextMenuListener(){const video=document.getElementById('cerberus-video');if(!video){setTimeout(addContextMenuListener,100);return}
video.addEventListener('contextmenu',function(e){e.preventDefault();createCerberusContextMenuAt(e.clientX,e.clientY);return!1})}
addContextMenuListener()